export default {
  HOME: '/',
  PORTFOLIO: '/portfolio',
  RECEIVE: '/receive',
  SEND_TX: '/send-tx',
  TX_HISTORY: '/tx-history',
  ACTIVE_CONTRACTS: '/active-contracts',
  EXECUTE_CONTRACT: '/execute-contract',
  FAUCET: '/faucet',
  LOADING: '/loading',
  UNLOCK_WALLET: '/unlock-wallet',
  SETTINGS: '/settings',
  // Onboarding routes
  WELCOME_MESSAGES: '/welcome-messages',
  IMPORT_OR_CREATE_WALLET: '/import-or-create-wallet',
  IMPORT_WALLET: '/import-wallet',
  SECRET_PHRASE: '/secret-phrase',
  SECRET_PHRASE_QUIZ: '/secret-phrase-quiz',
  SET_PASSWORD: '/set-password',
  TERMS_OF_SERVICE: '/terms-of-service',
  ERROR_REPORTING_OPT_IN: '/error-reporting-opt-in',
}
